import os
from crewai import Agent
from crewai.tools import tool
from github import Github


def create_github_pr(target_file: str, generated_code: str, task_description: str) -> str:
    """
    Core PR creation logic. Called by both the CrewAI tool and the web approval endpoint.

    Args:
        target_file: Path to the file to create or update in the repo.
        generated_code: Full file contents to commit.
        task_description: Human-readable description used as the PR title and branch name.

    Returns:
        A string starting with 'SUCCESS: ...' or 'ERROR: ...'.
    """
    try:
        github_token = os.getenv("GITHUB_TOKEN")
        repo_name = os.getenv("GITHUB_REPO")

        if not github_token or not repo_name:
            return "ERROR: GITHUB_TOKEN and GITHUB_REPO must be set in .env"

        g = Github(github_token)
        repo = g.get_repo(repo_name)

        default_branch = repo.default_branch
        base_sha = repo.get_branch(default_branch).commit.sha

        branch_name = f"devassist/{task_description[:40].replace(' ', '-').lower()}"

        # Re-use existing branch if it already exists (e.g. from a previous eval run)
        try:
            repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=base_sha)
        except Exception:
            pass  # Branch already exists — will update the file on it

        try:
            current_file = repo.get_contents(target_file, ref=default_branch)
            file_sha = current_file.sha
            repo.update_file(
                path=target_file,
                message=f"DevAssist: {task_description}",
                content=generated_code,
                sha=file_sha,
                branch=branch_name,
            )
        except Exception:
            repo.create_file(
                path=target_file,
                message=f"DevAssist: {task_description}",
                content=generated_code,
                branch=branch_name,
            )

        pr = repo.create_pull(
            title=f"DevAssist: {task_description}",
            body=(
                f"**Auto-generated by DevAssist**\n\n"
                f"**Task:** {task_description}\n\n"
                f"**File changed:** `{target_file}`\n\n"
                f"This PR was created automatically by the DevAssist AI pipeline."
            ),
            head=branch_name,
            base=default_branch,
        )

        return f"SUCCESS: PR created at {pr.html_url}"

    except Exception as e:
        return f"ERROR creating PR: {str(e)}"


@tool("GitHub PR Tool")
def github_pr_tool(input_data: str) -> str:
    """
    Creates a GitHub Pull Request with the generated code changes.
    Input format (pipe-separated): target_file|generated_code|task_description
    """
    parts = input_data.strip().split("|", 2)
    if len(parts) != 3:
        return "ERROR: Input must be: target_file|generated_code|task_description"

    target_file, generated_code, task_description = parts
    return create_github_pr(target_file, generated_code, task_description)


def make_pr_agent():
    return Agent(
        role="GitHub PR Agent",
        goal=(
            "Create a GitHub Pull Request with the reviewed and approved code changes. "
            "Use the GitHub PR Tool. "
            "Format input exactly as: target_file|generated_code|task_description"
        ),
        backstory=(
            "You are a DevOps engineer responsible for shipping code. "
            "You take approved code and open clean Pull Requests on GitHub. "
            "You format tool inputs precisely and report the PR URL."
        ),
        tools=[github_pr_tool],
        verbose=True,
        allow_delegation=False,
    )
